In [32]:
import pandas as pd
import numpy as np
import matplotlib as plt
import sklearn as sk

In [33]:
# Charger et visualiser dataframe
path = r"C:\DATA\Projets\2026_07_DESU_Data_sicences\Projets\Devoir_Machine_learning\dataset-openfoodfacts.csv"
df = pd.read_csv(path, nrows = 1000, sep='\t')
print(df.head())

   code                                                url  creator  \
0    54  http://world-en.openfoodfacts.org/product/0000...  kiliweb
1    63  http://world-en.openfoodfacts.org/product/0000...  kiliweb
2   114  http://world-en.openfoodfacts.org/product/0000...  kiliweb
3   431  http://world-en.openfoodfacts.org/product/0000...  kiliweb
4   105  http://world-en.openfoodfacts.org/product/0000...  kiliweb

    created_t      created_datetime  last_modified_t last_modified_datetime  \
0  1582569031  2020-02-24T18:30:31Z       1733085204   2024-12-01T20:33:24Z
1  1673620307  2023-01-13T14:31:47Z       1750061386   2025-06-16T08:09:46Z
2  1580066482  2020-01-26T19:21:22Z       1751035658   2025-06-27T14:47:38Z
3  1714301712  2024-04-28T10:55:12Z       1714301721   2024-04-28T10:55:21Z
4  1572117743  2019-10-26T19:22:23Z       1738073570   2025-01-28T14:12:50Z

  last_modified_by  last_updated_t last_updated_datetime  ... choline_100g  \
0              NaN      1740205422  2025-02-22T06:23:42Z  ...          NaN
1      bodysupport      1750061386  2025-06-16T08:09:46Z  ...          NaN
2         teolemon      1751035658  2025-06-27T14:47:38Z  ...          NaN
3          kiliweb      1714301721  2024-04-28T10:55:21Z  ...          NaN
4              NaN      1743653496  2025-04-03T04:11:36Z  ...          NaN

   phylloquinone_100g beta-glucan_100g inositol_100g carnitine_100g  \
0                 NaN              NaN           NaN            NaN
1                 NaN              NaN           NaN            NaN
2                 NaN              NaN           NaN            NaN
3                 NaN              NaN           NaN            NaN
4                 NaN              NaN           NaN            NaN

  sulphate_100g nitrate_100g acidity_100g carbohydrates-total_100g water_100g
0           NaN          NaN          NaN                      NaN        NaN
1           NaN          NaN          NaN                      NaN        NaN
2           NaN          NaN          NaN                      NaN        NaN
3           NaN          NaN          NaN                      NaN        NaN
4           NaN          NaN          NaN                      NaN        NaN

[5 rows x 211 columns]

In [34]:
# Description dataset
print(len(df.columns))   # Nombre de colonnes (équivalent de ncol sous R)
print(len(df.index))   # Nombre de lignes (équivalent de nrow sous R)

211
1000

In [35]:
# Extraire les noms des variables

list(df.columns.values)

['code',
 'url',
 'creator',
 'created_t',
 'created_datetime',
 'last_modified_t',
 'last_modified_datetime',
 'last_modified_by',
 'last_updated_t',
 'last_updated_datetime',
 'product_name',
 'abbreviated_product_name',
 'generic_name',
 'quantity',
 'packaging',
 'packaging_tags',
 'packaging_en',
 'packaging_text',
 'brands',
 'brands_tags',
 'brands_en',
 'categories',
 'categories_tags',
 'categories_en',
 'origins',
 'origins_tags',
 'origins_en',
 'manufacturing_places',
 'manufacturing_places_tags',
 'labels',
 'labels_tags',
 'labels_en',
 'emb_codes',
 'emb_codes_tags',
 'first_packaging_code_geo',
 'cities',
 'cities_tags',
 'purchase_places',
 'stores',
 'countries',
 'countries_tags',
 'countries_en',
 'ingredients_text',
 'ingredients_tags',
 'ingredients_analysis_tags',
 'allergens',
 'allergens_en',
 'traces',
 'traces_tags',
 'traces_en',
 'serving_size',
 'serving_quantity',
 'no_nutrition_data',
 'additives_n',
 'additives',
 'additives_tags',
 'additives_en',
 'nutriscore_score',
 'nutriscore_grade',
 'nova_group',
 'pnns_groups_1',
 'pnns_groups_2',
 'food_groups',
 'food_groups_tags',
 'food_groups_en',
 'states',
 'states_tags',
 'states_en',
 'brand_owner',
 'environmental_score_score',
 'environmental_score_grade',
 'nutrient_levels_tags',
 'product_quantity',
 'owner',
 'data_quality_errors_tags',
 'unique_scans_n',
 'popularity_tags',
 'completeness',
 'last_image_t',
 'last_image_datetime',
 'main_category',
 'main_category_en',
 'image_url',
 'image_small_url',
 'image_ingredients_url',
 'image_ingredients_small_url',
 'image_nutrition_url',
 'image_nutrition_small_url',
 'energy-kj_100g',
 'energy-kcal_100g',
 'energy_100g',
 'energy-from-fat_100g',
 'fat_100g',
 'saturated-fat_100g',
 'butyric-acid_100g',
 'caproic-acid_100g',
 'caprylic-acid_100g',
 'capric-acid_100g',
 'lauric-acid_100g',
 'myristic-acid_100g',
 'palmitic-acid_100g',
 'stearic-acid_100g',
 'arachidic-acid_100g',
 'behenic-acid_100g',
 'lignoceric-acid_100g',
 'cerotic-acid_100g',
 'montanic-acid_100g',
 'melissic-acid_100g',
 'unsaturated-fat_100g',
 'monounsaturated-fat_100g',
 'omega-9-fat_100g',
 'polyunsaturated-fat_100g',
 'omega-3-fat_100g',
 'omega-6-fat_100g',
 'alpha-linolenic-acid_100g',
 'eicosapentaenoic-acid_100g',
 'docosahexaenoic-acid_100g',
 'linoleic-acid_100g',
 'arachidonic-acid_100g',
 'gamma-linolenic-acid_100g',
 'dihomo-gamma-linolenic-acid_100g',
 'oleic-acid_100g',
 'elaidic-acid_100g',
 'gondoic-acid_100g',
 'mead-acid_100g',
 'erucic-acid_100g',
 'nervonic-acid_100g',
 'trans-fat_100g',
 'cholesterol_100g',
 'carbohydrates_100g',
 'sugars_100g',
 'added-sugars_100g',
 'sucrose_100g',
 'glucose_100g',
 'fructose_100g',
 'galactose_100g',
 'lactose_100g',
 'maltose_100g',
 'maltodextrins_100g',
 'psicose_100g',
 'starch_100g',
 'polyols_100g',
 'erythritol_100g',
 'isomalt_100g',
 'maltitol_100g',
 'sorbitol_100g',
 'fiber_100g',
 'soluble-fiber_100g',
 'polydextrose_100g',
 'insoluble-fiber_100g',
 'proteins_100g',
 'casein_100g',
 'serum-proteins_100g',
 'nucleotides_100g',
 'salt_100g',
 'added-salt_100g',
 'sodium_100g',
 'alcohol_100g',
 'vitamin-a_100g',
 'beta-carotene_100g',
 'vitamin-d_100g',
 'vitamin-e_100g',
 'vitamin-k_100g',
 'vitamin-c_100g',
 'vitamin-b1_100g',
 'vitamin-b2_100g',
 'vitamin-pp_100g',
 'vitamin-b6_100g',
 'vitamin-b9_100g',
 'folates_100g',
 'vitamin-b12_100g',
 'biotin_100g',
 'pantothenic-acid_100g',
 'silica_100g',
 'bicarbonate_100g',
 'potassium_100g',
 'chloride_100g',
 'calcium_100g',
 'phosphorus_100g',
 'iron_100g',
 'magnesium_100g',
 'zinc_100g',
 'copper_100g',
 'manganese_100g',
 'fluoride_100g',
 'selenium_100g',
 'chromium_100g',
 'molybdenum_100g',
 'iodine_100g',
 'caffeine_100g',
 'taurine_100g',
 'methylsulfonylmethane_100g',
 'hydroxymethylbutyrate_100g',
 'ph_100g',
 'fruits-vegetables-legumes_100g',
 'collagen-meat-protein-ratio_100g',
 'cocoa_100g',
 'chlorophyl_100g',
 'carbon-footprint_100g',
 'glycemic-index_100g',
 'water-hardness_100g',
 'choline_100g',
 'phylloquinone_100g',
 'beta-glucan_100g',
 'inositol_100g',
 'carnitine_100g',
 'sulphate_100g',
 'nitrate_100g',
 'acidity_100g',
 'carbohydrates-total_100g',
 'water_100g']

In [23]:
df.head(500)

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,last_modified_by,last_updated_t,last_updated_datetime,...,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g,sulphate_100g,nitrate_100g,acidity_100g,carbohydrates-total_100g,water_100g
0,54,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1582569031,2020-02-24T18:30:31Z,1733085204,2024-12-01T20:33:24Z,NaN,1740205422,2025-02-22T06:23:42Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,63,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1673620307,2023-01-13T14:31:47Z,1750061386,2025-06-16T08:09:46Z,bodysupport,1750061386,2025-06-16T08:09:46Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,114,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1580066482,2020-01-26T19:21:22Z,1751035658,2025-06-27T14:47:38Z,teolemon,1751035658,2025-06-27T14:47:38Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,431,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1714301712,2024-04-28T10:55:12Z,1714301721,2024-04-28T10:55:21Z,kiliweb,1714301721,2024-04-28T10:55:21Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1572117743,2019-10-26T19:22:23Z,1738073570,2025-01-28T14:12:50Z,NaN,1743653496,2025-04-03T04:11:36Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,625,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1571139104,2019-10-15T11:31:44Z,1629550852,2021-08-21T13:00:52Z,teolemon,1743591231,2025-04-02T10:53:51Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,628,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1539247161,2018-10-11T08:39:21Z,1728034856,2024-10-04T09:40:56Z,fix-code-bot,1743352623,2025-03-30T16:37:03Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,632,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1596293202,2020-08-01T14:46:42Z,1613815238,2021-02-20T10:00:38Z,NaN,1740089421,2025-02-20T22:10:21Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,633,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1568810477,2019-09-18T12:41:17Z,1596278000,2020-08-01T10:33:20Z,roboto-app,1740146720,2025-02-21T14:05:20Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,634,http://world-en.openfoodfacts.org/product/0000...,smoothie-app,1728483762,2024-10-09T14:22:42Z,1730518124,2024-11-02T03:28:44Z,spotter,1743247569,2025-03-29T11:26:09Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.head(500)

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,last_modified_by,last_updated_t,last_updated_datetime,...,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g,sulphate_100g,nitrate_100g,acidity_100g,carbohydrates-total_100g,water_100g
0,54,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1582569031,2020-02-24T18:30:31Z,1733085204,2024-12-01T20:33:24Z,NaN,1740205422,2025-02-22T06:23:42Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,63,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1673620307,2023-01-13T14:31:47Z,1750061386,2025-06-16T08:09:46Z,bodysupport,1750061386,2025-06-16T08:09:46Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,114,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1580066482,2020-01-26T19:21:22Z,1751035658,2025-06-27T14:47:38Z,teolemon,1751035658,2025-06-27T14:47:38Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,431,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1714301712,2024-04-28T10:55:12Z,1714301721,2024-04-28T10:55:21Z,kiliweb,1714301721,2024-04-28T10:55:21Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1572117743,2019-10-26T19:22:23Z,1738073570,2025-01-28T14:12:50Z,NaN,1743653496,2025-04-03T04:11:36Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Sélection des colonnes 
    # Colonnes qui composent le nutriscore uniquement ??

# Gestion des données manquantes

In [ ]:
# Exploration des NAs

path = r"C:\DATA\Projets\2026_07_DESU_Data_sicences\Projets\Devoir_Machine_learning\dataset-openfoodfacts.csv"


colonnes_cibles = [
'nutriscore_score', 
 'nutriscore_grade',
 'energy-kj_100g',
 'energy-kcal_100g',
 'energy_100g',
 'energy-from-fat_100g',
 'fat_100g',
 'saturated-fat_100g',
 'butyric-acid_100g',
 'caproic-acid_100g',
 'caprylic-acid_100g',
 'capric-acid_100g',
 'lauric-acid_100g',
 'myristic-acid_100g',
 'palmitic-acid_100g',
 'stearic-acid_100g',
 'arachidic-acid_100g',
 'behenic-acid_100g',
 'lignoceric-acid_100g',
 'cerotic-acid_100g',
 'montanic-acid_100g',
 'melissic-acid_100g',
 'unsaturated-fat_100g',
 'monounsaturated-fat_100g',
 'omega-9-fat_100g',
 'polyunsaturated-fat_100g',
 'omega-3-fat_100g',
 'omega-6-fat_100g',
 'alpha-linolenic-acid_100g',
 'eicosapentaenoic-acid_100g',
 'docosahexaenoic-acid_100g',
 'linoleic-acid_100g',
 'arachidonic-acid_100g',
 'gamma-linolenic-acid_100g',
 'dihomo-gamma-linolenic-acid_100g',
 'oleic-acid_100g',
 'elaidic-acid_100g',
 'gondoic-acid_100g',
 'mead-acid_100g',
 'erucic-acid_100g',
 'nervonic-acid_100g',
 'trans-fat_100g',
 'cholesterol_100g',
 'carbohydrates_100g',
 'sugars_100g',
 'added-sugars_100g',
 'sucrose_100g',
 'glucose_100g',
 'fructose_100g',
 'galactose_100g',
 'lactose_100g',
 'maltose_100g',
 'maltodextrins_100g',
 'psicose_100g',
 'starch_100g',
 'polyols_100g',
 'erythritol_100g',
 'isomalt_100g',
 'maltitol_100g',
 'sorbitol_100g',
 'fiber_100g',
 'soluble-fiber_100g',
 'polydextrose_100g',
 'insoluble-fiber_100g',
 'proteins_100g',
 'casein_100g',
 'serum-proteins_100g',
 'nucleotides_100g',
 'salt_100g',
 'added-salt_100g',
 'sodium_100g',
 'alcohol_100g',
 'vitamin-a_100g',
 'beta-carotene_100g',
 'vitamin-d_100g',
 'vitamin-e_100g',
 'vitamin-k_100g',
 'vitamin-c_100g',
 'vitamin-b1_100g',
 'vitamin-b2_100g',
 'vitamin-pp_100g',
 'vitamin-b6_100g',
 'vitamin-b9_100g',
 'folates_100g',
 'vitamin-b12_100g',
 'biotin_100g',
 'pantothenic-acid_100g',
 'silica_100g',
 'bicarbonate_100g',
 'potassium_100g',
 'chloride_100g',
 'calcium_100g',
 'phosphorus_100g',
 'iron_100g',
 'magnesium_100g',
 'zinc_100g',
 'copper_100g',
 'manganese_100g',
 'fluoride_100g',
 'selenium_100g',
 'chromium_100g',
 'molybdenum_100g',
 'iodine_100g',
 'caffeine_100g',
 'taurine_100g',
 'methylsulfonylmethane_100g',
 'hydroxymethylbutyrate_100g',
 'ph_100g',
 'fruits-vegetables-legumes_100g',
 'collagen-meat-protein-ratio_100g',
 'cocoa_100g',
 'chlorophyl_100g',
 'carbon-footprint_100g',
 'glycemic-index_100g',
 'water-hardness_100g',
 'choline_100g',
 'phylloquinone_100g',
 'beta-glucan_100g',
 'inositol_100g',
 'carnitine_100g',
 'sulphate_100g',
 'nitrate_100g',
 'acidity_100g',
 'carbohydrates-total_100g',
 'water_100g']  # à adapter

# Dictionnaire pour accumuler les comptes
missing_counts = {col: 0 for col in colonnes_cibles}
total_rows = 0

chunksize = 10_000  # ajustez selon votre RAM

for chunk in pd.read_csv(
    path,
    sep='\t',              # OFF utilise des tabulations
    usecols=colonnes_cibles,  # ne charge QUE les colonnes utiles
    chunksize=chunksize,
    low_memory=False,
    on_bad_lines='skip'
):
    total_rows += len(chunk)
    for col in colonnes_cibles:
        missing_counts[col] += chunk[col].isna().sum()

print(f"Total lignes traitées : {total_rows}")
for col, n in missing_counts.items():
    pct = 100 * n / total_rows
    print(f"{col}: {n} manquants ({pct:.2f}%)")

Total lignes traitées : 4532767
nutriscore_score: 3157914 manquants (69.67%)
nutriscore_grade: 44185 manquants (0.97%)
energy-kj_100g: 2333408 manquants (51.48%)
energy-kcal_100g: 2297803 manquants (50.69%)
energy_100g: 2296811 manquants (50.67%)
energy-from-fat_100g: 4532288 manquants (99.99%)
fat_100g: 2321516 manquants (51.22%)
saturated-fat_100g: 2404676 manquants (53.05%)
butyric-acid_100g: 4532736 manquants (100.00%)
caproic-acid_100g: 4532753 manquants (100.00%)
caprylic-acid_100g: 4532750 manquants (100.00%)
capric-acid_100g: 4532747 manquants (100.00%)
lauric-acid_100g: 4532737 manquants (100.00%)
myristic-acid_100g: 4532741 manquants (100.00%)
palmitic-acid_100g: 4532716 manquants (100.00%)
stearic-acid_100g: 4532742 manquants (100.00%)
arachidic-acid_100g: 4532539 manquants (99.99%)
behenic-acid_100g: 4532674 manquants (100.00%)
lignoceric-acid_100g: 4532748 manquants (100.00%)
cerotic-acid_100g: 4532755 manquants (100.00%)
montanic-acid_100g: 4532742 manquants (100.00%)
melissic-acid_100g: 4532743 manquants (100.00%)
unsaturated-fat_100g: 4532602 manquants (100.00%)
monounsaturated-fat_100g: 4505172 manquants (99.39%)
omega-9-fat_100g: 4532752 manquants (100.00%)
polyunsaturated-fat_100g: 4505473 manquants (99.40%)
omega-3-fat_100g: 4532026 manquants (99.98%)
omega-6-fat_100g: 4532430 manquants (99.99%)
alpha-linolenic-acid_100g: 4531524 manquants (99.97%)
eicosapentaenoic-acid_100g: 4532504 manquants (99.99%)
docosahexaenoic-acid_100g: 4532309 manquants (99.99%)
linoleic-acid_100g: 4532093 manquants (99.99%)
arachidonic-acid_100g: 4532540 manquants (99.99%)
gamma-linolenic-acid_100g: 4532754 manquants (100.00%)
dihomo-gamma-linolenic-acid_100g: 4532744 manquants (100.00%)
oleic-acid_100g: 4532644 manquants (100.00%)
elaidic-acid_100g: 4532758 manquants (100.00%)
gondoic-acid_100g: 4532721 manquants (100.00%)
mead-acid_100g: 4532747 manquants (100.00%)
erucic-acid_100g: 4532757 manquants (100.00%)
nervonic-acid_100g: 4532750 manquants (100.00%)
trans-fat_100g: 4416162 manquants (97.43%)
cholesterol_100g: 4180332 manquants (92.22%)
carbohydrates_100g: 2321025 manquants (51.21%)
sugars_100g: 2388528 manquants (52.69%)
added-sugars_100g: 3764011 manquants (83.04%)
sucrose_100g: 4295878 manquants (94.77%)
glucose_100g: 4295564 manquants (94.77%)
fructose_100g: 4295601 manquants (94.77%)
galactose_100g: 4299167 manquants (94.85%)
lactose_100g: 4294991 manquants (94.75%)
maltose_100g: 4296102 manquants (94.78%)
maltodextrins_100g: 4532553 manquants (100.00%)
psicose_100g: 4532738 manquants (100.00%)
starch_100g: 4263213 manquants (94.05%)
polyols_100g: 4284724 manquants (94.53%)
erythritol_100g: 4532642 manquants (100.00%)
isomalt_100g: 4532766 manquants (100.00%)
maltitol_100g: 4532753 manquants (100.00%)
sorbitol_100g: 4532754 manquants (100.00%)
fiber_100g: 3500514 manquants (77.23%)
soluble-fiber_100g: 4531766 manquants (99.98%)
polydextrose_100g: 4532761 manquants (100.00%)
insoluble-fiber_100g: 4531939 manquants (99.98%)
proteins_100g: 2317841 manquants (51.14%)
casein_100g: 4532676 manquants (100.00%)
serum-proteins_100g: 4532656 manquants (100.00%)
nucleotides_100g: 4532723 manquants (100.00%)
salt_100g: 2580977 manquants (56.94%)
added-salt_100g: 4532693 manquants (100.00%)
sodium_100g: 2580977 manquants (56.94%)
alcohol_100g: 4257759 manquants (93.93%)
vitamin-a_100g: 4253467 manquants (93.84%)
beta-carotene_100g: 4300283 manquants (94.87%)
vitamin-d_100g: 4255968 manquants (93.89%)
vitamin-e_100g: 4256227 manquants (93.90%)
vitamin-k_100g: 4501067 manquants (99.30%)
vitamin-c_100g: 4239465 manquants (93.53%)
vitamin-b1_100g: 4297092 manquants (94.80%)
vitamin-b2_100g: 4296913 manquants (94.80%)
vitamin-pp_100g: 4291873 manquants (94.69%)
vitamin-b6_100g: 4284840 manquants (94.53%)
vitamin-b9_100g: 4298477 manquants (94.83%)
folates_100g: 4530922 manquants (99.96%)
vitamin-b12_100g: 4297558 manquants (94.81%)
biotin_100g: 4530763 manquants (99.96%)
pantothenic-acid_100g: 4293445 manquants (94.72%)
silica_100g: 4532497 manquants (99.99%)
bicarbonate_100g: 4531724 manquants (99.98%)
potassium_100g: 4196626 manquants (92.58%)
chloride_100g: 4516945 manquants (99.65%)
calcium_100g: 4174533 manquants (92.10%)
phosphorus_100g: 4257202 manquants (93.92%)
iron_100g: 4170774 manquants (92.01%)
magnesium_100g: 4253686 manquants (93.84%)
zinc_100g: 4257236 manquants (93.92%)
copper_100g: 4262358 manquants (94.03%)
manganese_100g: 4262012 manquants (94.03%)
fluoride_100g: 4531276 manquants (99.97%)
selenium_100g: 4273518 manquants (94.28%)
chromium_100g: 4532357 manquants (99.99%)
molybdenum_100g: 4532306 manquants (99.99%)
iodine_100g: 4298012 manquants (94.82%)
caffeine_100g: 4499824 manquants (99.27%)
taurine_100g: 4532447 manquants (99.99%)
methylsulfonylmethane_100g: 4532766 manquants (100.00%)
hydroxymethylbutyrate_100g: 4532767 manquants (100.00%)
ph_100g: 4532160 manquants (99.99%)
fruits-vegetables-legumes_100g: 3805998 manquants (83.97%)
collagen-meat-protein-ratio_100g: 4532468 manquants (99.99%)
cocoa_100g: 4524524 manquants (99.82%)
chlorophyl_100g: 4532757 manquants (100.00%)
carbon-footprint_100g: 4532355 manquants (99.99%)
glycemic-index_100g: 4532758 manquants (100.00%)
water-hardness_100g: 4532752 manquants (100.00%)
choline_100g: 4494057 manquants (99.15%)
phylloquinone_100g: 4300236 manquants (94.87%)
beta-glucan_100g: 4532701 manquants (100.00%)
inositol_100g: 4532576 manquants (100.00%)
carnitine_100g: 4532603 manquants (100.00%)
sulphate_100g: 4532140 manquants (99.99%)
nitrate_100g: 4532361 manquants (99.99%)
acidity_100g: 4532731 manquants (100.00%)
carbohydrates-total_100g: 4530797 manquants (99.96%)
water_100g: 4288682 manquants (94.62%)

Retrait des variables avec NAs. Si % NA > X, retirer variable, sinon imputation.